version: '2'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: ~/data/postgres
    volumes:
        - ~/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    # networks:
    #   - postgres
    restart: unless-stopped
  
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    volumes:
       - ~/data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    # networks:
    #   - postgres
    restart: unless-stopped